[package]
name = "ros"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = "none"
lto = "fat"
opt-level = 3

[profile.test]
panic = "abort"

[build-dependencies]
cc = "1.2.53"
